---

- name: Create config directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 755
  with_items:
    - "{{ jenkins_config_dir }}"

- name: Copy jenkins dockerfiles
  become: yes
  copy:
    src: dockerfiles
    dest: "{{ jenkins_config_dir }}"
  notify: Restart docker-compose service

- name: Copy jenkins plugin files
  become: yes
  copy:
    src: jenkins_plugins
    dest: "{{ jenkins_config_dir }}"

- name: Assemble jenkins plugins.txt file
  become: yes
  assemble:
    src: "{{ jenkins_plugins_txt_dir }}"
    dest: "{{ jenkins_dockerfiles_dir }}/jenkins-controller/plugins.txt"
  notify: Restart docker-compose service

- name: Synchronize jenkins config files
  become: yes
  synchronize:
    src: "{{ inventory_hostname }}/jenkins/jenkins_config"
    dest: "{{ jenkins_config_dir }}"
    delete: yes
    recursive: yes
    owner: no
    group: no
  notify: Restart docker-compose service
