---

- name: "Create systemd service file: {{ compose_service_file_path }}"
  become: yes
  template:
    src: template.service
    dest: "{{ compose_service_file_path }}"
  register: service_file
  notify: Restart docker-compose service

- name: Reload systemd config files
  become: yes
  systemd:
    daemon_reload: yes
  when: service_file.changed

- name: "Create docker compose directory: {{ compose_service_dir }}"
  become: yes
  file:
    path: "{{ compose_service_dir }}"
    state: directory
    recurse: yes

- name: "Create docker compose file: {{ compose_file_path }}"
  become: yes
  template:
    src: "{{ inventory_hostname }}/docker-compose-service/docker-compose.yml"
    dest: "{{ compose_file_path }}"
  notify: Restart docker-compose service

- name: "Set enabled={{ compose_service_enabled }} for: {{ compose_service_name }}"
  become: yes
  systemd:
    name: "{{ compose_service_name }}"
    enabled: "{{ compose_service_enabled }}"

- name: Flush handlers
  meta: flush_handlers

- name: "Start service: {{ compose_service_name }}"
  become: yes
  systemd:
    name: "{{ compose_service_name }}"
    state: started
  notify: Restart docker-compose service
