---

# to provide
compose_service_name: "example"
compose_service_dependencies: []
compose_service_enabled: yes
compose_auto_restart_if_failing: no

# usually not needed to change
systemd_system_dir: "/etc/systemd/system"
compose_service_file_path: "{{ systemd_system_dir }}/{{ compose_service_name }}.service"
compose_dir: "/etc/docker-compose"
compose_service_dir: "{{ compose_dir }}/{{ compose_service_name }}"
compose_file_path: "{{ compose_service_dir }}/docker-compose.yml"
