jenkins:
  numExecutors: 0
  remotingSecurity:
    enabled: true
  nodes:
    - permanent:
        labelString: "docker"
        launcher:
          ssh:
            credentialsId: "modern-jenkins"
            host: "jenkins-ssh-agent-1"
            port: 22
            sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
        name: "ssh-agent-1"
        remoteFS: "/var/jenkins/agent-1"
        retentionStrategy: "always"
    - permanent:
        labelString: "docker"
        launcher:
          ssh:
            credentialsId: "modern-jenkins"
            host: "jenkins-ssh-agent-2"
            port: 22
            sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
        name: "ssh-agent-2"
        remoteFS: "/var/jenkins/agent-2"
        retentionStrategy: "always"

unclassified:
  location:
    adminAddress: "nobody@nowhere"
    url: "https://jenkins.localhost/"
  buildTimestamp:
    enableBuildTimestamp: true
    pattern: "yyyy-MM-dd_HH-mm-ss"
    timezone: "Europe/Zurich"
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
      - defaultBuildDiscarder:
          discarder:
            logRotator:
              artifactDaysToKeepStr: "50"
              artifactNumToKeepStr: "5"
              daysToKeepStr: "100"
              numToKeepStr: "10"
