jenkins:
  numExecutors: 0
  remotingSecurity:
    enabled: true
  nodes:
    - permanent:
        labelString: "docker"
        launcher:
          ssh:
            credentialsId: "modern-jenkins"
            host: "jenkins-agent-yocto"
            port: 22
            sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
        name: "yocto-agent"
        remoteFS: "/var/jenkins/agent"
        retentionStrategy: "always"

unclassified:
  location:
    adminAddress: "nobody@nowhere"
    url: "https://jenkins.localhost/"
  buildTimestamp:
    enableBuildTimestamp: true
    pattern: "yyyy-MM-dd_HH-mm-ss"
    timezone: "Europe/Zurich"
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
      - defaultBuildDiscarder:
          discarder:
            logRotator:
              artifactDaysToKeepStr: "50"
              artifactNumToKeepStr: "5"
              daysToKeepStr: "100"
              numToKeepStr: "10"
