---

- name: Create config directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  with_items:
    - "{{ jenkins_config_dir }}"

- name: Copy jenkins dockerfiles
  become: yes
  copy:
    src: dockerfiles
    dest: "{{ jenkins_config_dir }}"
  notify: Restart docker-compose service

- name: Copy jenkins plugin files
  become: yes
  copy:
    src: jenkins_plugins
    dest: "{{ jenkins_config_dir }}"

- name: Assemble jenkins plugins.txt file
  become: yes
  assemble:
    src: "{{ jenkins_plugins_txt_dir }}"
    dest: "{{ jenkins_dockerfiles_dir }}/jenkins-controller/plugins.txt"
  notify: Restart docker-compose service

- name: Create temporary directory
  tempfile:
    state: directory
  register: temp_dir
  changed_when: no

- name: Create config subdirectories
  file:
    path: "{{ temp_dir.path }}/jenkins_config/{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  with_filetree: "{{ inventory_hostname }}/jenkins-controller/jenkins_config"
  when: item.state == "directory"
  changed_when: no

- name: Template jenkins config files
  template:
    src: "{{ item.src }}"
    dest: "{{ temp_dir.path }}/jenkins_config/{{ item.path }}"
    mode: "{{ item.mode }}"
  with_filetree: "{{ inventory_hostname }}/jenkins-controller/jenkins_config"
  when: item.state == "file"
  changed_when: no

- name: Synchronize jenkins config files
  become: yes
  synchronize:
    src: "{{ temp_dir.path }}/jenkins_config"
    dest: "{{ jenkins_config_dir }}"
    delete: yes
    recursive: yes
    owner: no
    group: no
    times: no
    checksum: yes
  delegate_to: "{{ ansible_host }}"
  notify: Restart docker-compose service

- name: Cleanup temporary directory
  file:
    path: "{{ temp_dir.path }}"
    state: absent
  changed_when: no
