---

- name: Create config directory
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  with_items:
    - "{{ caddy_config_dir }}"

- name: Create temporary directory
  tempfile:
    state: directory
  register: temp_dir
  changed_when: no

- name: Create config subdirectories
  file:
    path: "{{ temp_dir.path }}/{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  with_filetree: "{{ inventory_hostname }}/caddy"
  when: item.state == "directory"
  changed_when: no

- name: Template caddy files
  template:
    src: "{{ item.src }}"
    dest: "{{ temp_dir.path }}/{{ item.path }}"
    mode: "{{ item.mode }}"
  with_filetree: "{{ inventory_hostname }}/caddy"
  when: item.state == "file"
  changed_when: no

- name: Synchronize caddy config files
  become: yes
  synchronize:
    src: "{{ temp_dir.path }}/"
    dest: "{{ caddy_config_dir }}"
    delete: yes
    recursive: yes
    owner: no
    group: no
    times: no
    checksum: yes
  delegate_to: "{{ ansible_host }}"
  notify: Restart docker-compose service

- name: Cleanup temporary directory
  file:
    path: "{{ temp_dir.path }}"
    state: absent
  changed_when: no
