---

- name: Install shiftfs for Debian
  import_tasks: debian.yml
  when: ansible_distribution == 'Debian'

- name: Install sysbox deb package
  become: yes
  apt:
    deb: https://downloads.nestybox.com/sysbox/releases/v0.5.0/sysbox-ce_0.5.0-0.linux_amd64.deb
