name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: macos-10.15
    env:
      VAGRANT_DISABLE_VBOXSYMLINKCREATE: "1"

    steps:
    - uses: actions/checkout@v2

    - name: Run vagrant up virtualbox-ubuntu2204
      run: vagrant up virtualbox-ubuntu2204
